name: Gestão vagas Application

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
      - name: Build Project
        uses: mvn clean install
      - name: Login docker
        uses: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}} 
      - name: Build docker image
        uses: docker build -t gabrielmendes0/gestao_vagas .
      - name: Publish image
        uses: docker push gabrielmendes0/gestao_vagas
  
##
      